### ISSUE TITLE
创建容器不填写映射端口的话 ssh以及Jupyter地址将不显示

### ISSUE THREAD

**Issue by hansonkwok** [zuiyue-com/wei#13]
<img width="272" alt="1708487073299" src="https://github.com/zuiyue-com/wei/assets/160584505/b9d7b975-12f6-41af-8d68-e58afeafe11c">
<img width="425" alt="1708487245025" src="https://github.com/zuiyue-com/wei/assets/160584505/e84978c7-9d0f-4663-b131-9dc4ff0973c0">

**Comment by rustburn** [comment]
创建容器不填写映射端口，是不会实现穿透功能，功能无误，符合设计。
