### ISSUE TITLE
创建容器时镜像名冲突问题

### ISSUE THREAD

**Issue by ztfcharlie** [zuiyue-com/wei#18]
复现：
用  ivories/redis 创建一个名字叫 redis的容器，这时，镜像会生成一个redis的镜像，创建完成后，删除redis容器。
如果此刻，我想创建一个ivories/redis的镜像创建一个叫redis的容器，就会默认使用了当前镜像列表的redis镜像，但是这个镜像却是前面创建的，不是真正想要的ivories/redis的镜像

**Comment by rustburn** [comment]
无法复现
